/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.deportistas.views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import com.deportistas.models.disciplinas.Disciplina;
import com.deportistas.models.disciplinas.ListaDisciplina;

/**
 *
 * @author enaldo1709
 */
public class AddDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form AddDisciplina
     */
    public AddDisciplina(ListaDisciplina disciplinas) {
        initComponents();
        this.disciplinas =disciplinas;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        disciplinaField = new javax.swing.JTextField();
        acceptAddDisciplina = new javax.swing.JButton();
        cancelAddDisciplina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tipo de letra del sistema", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Disciplina");

        jLabel2.setText("Disciplina:");

        acceptAddDisciplina.setText("Agregar");
        acceptAddDisciplina.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt){
                acceptAddDeportistaActionPerformed(evt);
            }
        });

        cancelAddDisciplina.setText("Cancelar");
        cancelAddDisciplina.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt){
                cancelAddDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(disciplinaField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptAddDisciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelAddDisciplina)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(disciplinaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptAddDisciplina)
                    .addComponent(cancelAddDisciplina))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void cancelAddDisciplinaActionPerformed(ActionEvent evt){
        this.dispose();
    }

    private void acceptAddDeportistaActionPerformed(ActionEvent evt){
        try{
            String nombre = this.disciplinaField.getText();
            this.disciplinas.add(nombre);
            this.dispose();
        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error la disciplina no puede ser nula",
                "Error agregando disciplina", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e)  {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error agregando disciplina", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptAddDisciplina;
    private javax.swing.JButton cancelAddDisciplina;
    private javax.swing.JTextField disciplinaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private ListaDisciplina disciplinas;
}
